services:
  app:
    build: . 
    container_name: note_taking_app
    ports:
      - "3000:3000"
    volumes:
      - ./website:/website  
      - ./instance:/app/instance  
    environment:
      - FLASK_ENV=development
   